### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mansona/lint-to-the-future-dashboard-action#3]
> You can read the README of the that project to find out more about it 

was reading https://github.com/mansona/lint-to-the-future#lint-to-the-future-dashboard and it said to read the README of this project.

I read it, and I did not find out more about it :upside_down_face: 
code seems legit tho: https://github.com/mansona/lint-to-the-future-dashboard-action/blob/main/.github/workflows/dashboard.yml, and will be fine for now <3

**Comment by mansona** [comment]
This has been fixed since v1 that I released today 👍
